menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  类别: /categories/ || fas fa-folder-open
  摸鱼||fas fa-heartbeat:
    - 音乐 || /music/ || fas fa-music
    - 动漫 || /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

highlight_theme: mac

highlight_copy: true